name: 🚀 Feature Request
description: Suggest a Python-CI-Template idea
# title: " "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a Python-CI-Template 🚀 Feature Request!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/ozora-ogino/python-ci-template/issues) to see if a similar feature request already exists.
      options:
        - label: >
            I have searched the Python-CI-Template [issues](https://github.com/ozora-ogino/python-ci-template/issues) and found no similar feature requests.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A short description of your feature.
      placeholder: |
        What new feature would you like to see in Python-CI-Template?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use case
      description: |
        Describe the use case of your feature request. It will help us understand and prioritize the feature request.
      placeholder: |
        How would this feature be used, and who would use it?

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/ozora-ogino/python-ci-template/pulls) (PR) to help improve python-ci-template for everyone, especially if you have a good understanding of how to implement a fix or feature.
        See the Python-CI-Template [Contributing Guide](https://github.com/ozora-ogino/python-ci-template/blob/master/CONTRIBUTING.md) to get started.
      options:
        - label: Yes I'd like to help by submitting a PR!